[package]
name = "flopen"
version = "0.1.0"
authors = ["Andrej Shadura <andrew.shadura@collabora.co.uk>"]
description = "Reliably open and lock a file"
edition = "2018"
license = "MIT"
repository = "https://github.com/andrewshadura/rust-flopen"

[target.'cfg(unix)'.dependencies]
nix = "0"

[dev-dependencies]
tempfile = "3"
